[package]
name = "sync"
version = "0.1.0"
authors = ["Hanh <hanh425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "scan_all"
harness = false

[[bin]]
name = "warp-cli"
path = "src/main/warp_cli.rs"

[[bin]]
name = "test_hash"
path = "src/main/test.rs"

[[bin]]
name = "sign"
path = "src/main/sign.rs"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.8.4"
anyhow = "1.0.40"
thiserror = "1.0.25"
log = "0.4.14"
flexi_logger = {version="0.17.1", features = ["compress"]}
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
bincode = "1.3.3"
tokio = { version = "^1.6", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.7"
protobuf = "2.23.0"
hex = "0.4.3"
futures = "0.3.15"
tonic = {version = "0.4.3", features = ["tls", "tls-roots"]}
prost = "0.7"
rayon = "1.5.1"
tiny-bip39 = "0.8"
rand = "0.8.4"
rusqlite = { version = "^0.24", features = ["bundled"] }
jubjub = "0.9.0"
bls12_381 = "0.7"
ff = "0.12"
group = "0.12"
byteorder = "^1.4"
secp256k1 = "0.21"
tiny-hderive = "0.3.0"
ripemd160 = "0.9.1"
sha2 = "0.9.5"
lazy_static = "1.4.0"
rustyline = "8.2.0"
clap = "2.3.3"
chrono = "0.4.19"
lazycell = "1.3.0"
reqwest = { version = "0.11.4", features = ["json", "rustls-tls"], default-features = false }

bech32 = "0.8.1"
rand_chacha = "0.3.1"
blake2b_simd = "0.5.11"
chacha20poly1305 = "0.9.0"
base64 = "^0.13"

ledger-apdu = { version = "0.8.0", optional = true }
hmac = { version = "0.12.1", optional = true }
ed25519-bip32 = { version = "0.4.1", optional = true }

orchard = { version = "0.1.0", features = [ "test-dependencies" ] }
pasta_curves = "0.4.0"
halo2_gadgets = "0.1.0"
incrementalmerkletree = "0.3.0"

[features]
ledger = ["ledger-apdu", "hmac", "ed25519-bip32"]

# librustzcash synced to 35023ed8ca2fb1061e78fd740b640d4eefcc5edd

[dependencies.zcash_client_backend]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"

[dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"
features = [ "transparent-inputs" ]

[dependencies.zcash_proofs]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"

[dependencies.zcash_params]
path = "../zcash-params"

[dependencies.zcash_address]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"

[dependencies.zcash_encoding]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"

[dependencies.zcash_note_encryption]
git = "https://github.com/hhanh00/librustzcash.git"
#rev = "c708380ef59b254f71a7d0b417e03f44fd267c2d"

[build-dependencies]
tonic-build = "0.4.2"

[dev-dependencies]
criterion = "0.3.4"
